# Generated by Django 5.2.4 on 2025-08-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0003_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourited_by', to='recipeapp.recipe'),
        ),
    ]
