# Generated by Django 5.2.4 on 2025-08-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0004_userprofile_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='procedure',
            field=models.TextField(blank=True),
        ),
    ]
