# Generated by Django 5.2.4 on 2025-08-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0005_recipe_procedure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
